import ProductCard from "@/components/ProductCard";
import { useState } from "react";
import { categorySlug, categories, products } from "@/lib/catalog";
import { useStore } from "@/contexts/StoreContext";
import { useCatalog } from "@/hooks/useCatalog";
import { Link } from "wouter";
import { ArrowRight, Box, CreditCard, Headphones, ShieldCheck, Sparkles } from "lucide-react";
import { FaWhatsapp } from "react-icons/fa";
import { logoImage } from "@/lib/inlineLogoAsset";
import { heroImage } from "@/lib/inlineHeroAsset";

const benefits = [
  { icon: CreditCard, title: "Parcele em até 3x", caption: "Sem juros no cartão" },
  { icon: Box, title: "Trocas em até 7 dias", caption: "Simples e sem burocracia" },
  { icon: Headphones, title: "Suporte especializado", caption: "Atendimento humanizado" },
  { icon: ShieldCheck, title: "Compra protegida", caption: "Pagamento seguro" },
];

export default function Home() {
  const { setCartOpen } = useStore();
  const { products: catalogProducts } = useCatalog();
  const highlights = catalogProducts.slice(0, 4);
  const [heroSrc, setHeroSrc] = useState(`${import.meta.env.BASE_URL}assets/overzied-hero.jpg`);
  return <main>
    <section className="relative isolate overflow-hidden border-b border-white/10"><div className="container grid min-h-[610px] items-center gap-8 py-14 lg:grid-cols-[.98fr_1.02fr] lg:py-16"><div className="relative z-10 max-w-xl"><div className="inline-flex items-center gap-2 rounded-full border border-[#7affb9]/30 bg-[#7affb9]/5 px-3 py-1.5 text-[10px] font-bold tracking-[.18em] text-[#8dffc3]"><Sparkles size={13} /> NOVO DROP — 2026</div><h1 className="display-title mt-7">SEU ESTILO.<br /><span className="text-[#7affb9]">SUA PRESENÇA.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-white/65">Moda masculina com atitude, peças selecionadas e entrega para todo o Brasil. Use o cupom <strong className="font-semibold text-white">BEMVINDO</strong> e garanta 5% OFF na primeira compra.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/categoria/kits" className="button-primary">VER KITS PROMOCIONAIS <ArrowRight size={17} /></Link><a className="button-secondary" target="_blank" rel="noreferrer" href="https://api.whatsapp.com/send?text=Olá!%20Vim%20pelo%20site%20da%20Overzied%20Modas.">FALAR NO WHATSAPP</a></div><div className="mt-10 flex items-center gap-4"><img src={logoImage} alt="OM" className="h-12 w-12 rounded-full object-cover opacity-85" /><p className="border-l border-white/15 pl-4 text-xs leading-5 text-white/45">OVERZIED MODAS<br /><span className="text-white/70">MODA QUE REPRESENTA VOCÊ.</span></p></div></div><div className="relative mx-auto w-full max-w-[600px] lg:mr-0"><div className="absolute -inset-12 rounded-full bg-[#7affb9]/10 blur-[90px]" /><div className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-[#12171b] p-2 shadow-[0_25px_80px_rgba(0,0,0,.45)]"><img src={heroSrc} onError={() => setHeroSrc(heroImage)} alt="Modelo vestindo moda urbana Overzied Modas" className="aspect-[4/4.6] w-full rounded-[1.55rem] object-cover object-right" /><div className="absolute bottom-8 left-8 rounded-xl border border-white/10 bg-black/60 px-4 py-3 backdrop-blur"><p className="text-[9px] font-bold tracking-[.2em] text-[#7affb9]">CURADORIA OM</p><p className="mt-1 text-sm font-semibold">Moda urbana premium</p></div></div></div></div><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_15%_25%,rgba(59,255,160,.1),transparent_26%),linear-gradient(110deg,#0a0d10_0%,#0e1419_60%,#080a0c_100%)]" /></section>
    <section className="border-b border-white/10 bg-[#0d1216]"><div className="container grid divide-y divide-white/10 sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-4">{benefits.map(({ icon: Icon, title, caption }) => <div key={title} className="flex items-center gap-3 px-3 py-6 sm:px-5"><span className="flex h-9 w-9 items-center justify-center rounded-full border border-white/15 bg-white/[.03] text-[#7affb9]"><Icon size={17} /></span><div><p className="text-sm font-semibold">{title}</p><p className="mt-0.5 text-xs text-white/45">{caption}</p></div></div>)}</div></section>
    <section className="container py-16 md:py-24"><div className="offer-panel overflow-hidden rounded-[2rem] p-7 md:p-11"><div className="relative z-10 max-w-xl"><p className="eyebrow text-[#7affb9]">PROMOÇÃO DA SEMANA</p><h2 className="mt-3 text-4xl font-black uppercase tracking-tight sm:text-5xl">KIT ESSENTIAL<br /><span className="text-white/55">POR R$ 149,90</span></h2><p className="mt-4 max-w-md text-sm leading-6 text-white/65">Duas camisetas de algodão premium para você renovar o visual pagando menos.</p><Link href="/produto/kit-urban-essential" className="button-primary mt-7">APROVEITAR AGORA <ArrowRight size={17} /></Link></div><div className="absolute -bottom-24 -right-8 hidden h-80 w-80 rounded-full border-[38px] border-[#7affb9]/15 lg:block" /></div></section>
    <section className="container pb-16"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">COLEÇÃO</p><h2 className="section-title mt-2">DESTAQUES DA SEMANA</h2></div><Link href="/categoria/camisetas" className="text-sm font-semibold text-[#7affb9] transition hover:text-white">VER TODOS <ArrowRight className="inline" size={15} /></Link></div><p className="mt-4 max-w-2xl text-sm leading-6 text-white/52">Peças versáteis e selecionadas para expressar a sua identidade. Encontre seu tamanho e leve a Overzied Modas com você.</p><div className="mt-8 grid grid-cols-2 gap-x-4 gap-y-9 md:grid-cols-3 lg:grid-cols-4">{highlights.map((product) => <ProductCard key={product.id} product={product} />)}</div></section>
    <section className="border-y border-white/10 bg-[#0d1216]"><div className="container py-16"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">EXPLORE</p><h2 className="section-title mt-2">ENCONTRE SEU ESTILO</h2></div><p className="max-w-xs text-sm leading-6 text-white/50">Uma seleção para cada momento, sempre com a identidade OM.</p></div><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">{categories.map((category, index) => <Link key={category} href={`/categoria/${categorySlug(category)}`} className="category-tile group" style={{ background: `linear-gradient(135deg, rgba(255,255,255,.06), ${catalogProducts[index % catalogProducts.length]?.color ?? "#7affb9"}18)` }}><span className="text-xs font-bold tracking-[.14em] text-white/45">0{index + 1}</span><span className="mt-10 block text-lg font-bold uppercase">{category}</span><ArrowRight className="mt-3 text-[#7affb9] transition duration-200 group-hover:translate-x-1" size={18} /></Link>)}</div></div></section>
    <section className="container py-16 md:py-24"><div className="grid items-center gap-8 rounded-[2rem] border border-white/10 bg-white/[.025] p-7 md:grid-cols-[1fr_auto] md:p-10"><div><p className="eyebrow">NOVIDADES</p><h2 className="section-title mt-2">NÃO PERCA O PRÓXIMO DROP</h2><p className="mt-3 max-w-xl text-sm leading-6 text-white/55">Cadastre seu e-mail e seja o primeiro a receber novidades, peças limitadas e condições especiais.</p></div><form onSubmit={(event) => { event.preventDefault(); setCartOpen(true); }} className="flex w-full max-w-md gap-2"><input required type="email" placeholder="Seu melhor e-mail" className="h-12 min-w-0 flex-1 rounded-xl border border-white/15 bg-black/20 px-4 text-sm outline-none transition focus:border-[#7affb9]" /><button className="button-primary shrink-0">QUERO RECEBER</button></form></div></section>
    <a href="https://api.whatsapp.com/send?text=Olá!%20Vim%20pelo%20site%20da%20Overzied%20Modas." target="_blank" rel="noreferrer" aria-label="Falar pelo WhatsApp" className="whatsapp-float"><FaWhatsapp aria-hidden="true" size={21} /><span>ATENDIMENTO</span></a>
  </main>;
}
