-- Overzied Modas — esquema inicial para Supabase/PostgreSQL.
-- Execute este arquivo no SQL Editor de um NOVO projeto Supabase, após revisar as instruções em supabase/README.md.
-- Este script não contém, não solicita e não armazena chaves Pix, dados de cartão ou credenciais do gateway.

create extension if not exists pgcrypto;
create extension if not exists pg_cron;

create schema if not exists app_private;
revoke all on schema app_private from public;

create type public.app_role as enum ('customer', 'admin');
create type public.product_category as enum (
  'Camisetas', 'Bermudas', 'Kits', 'Calças', 'Calçados', 'Esportivo', 'Perfumes', 'Acessórios'
);
create type public.payment_method as enum ('pix', 'credit', 'boleto');
create type public.payment_status as enum ('pending', 'approved', 'rejected', 'cancelled');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  role public.app_role not null default 'customer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 180),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  category public.product_category not null,
  description text not null,
  price_cents integer not null check (price_cents >= 0),
  compare_at_price_cents integer check (compare_at_price_cents is null or compare_at_price_cents >= price_cents),
  sizes jsonb not null default '[]'::jsonb check (jsonb_typeof(sizes) = 'array'),
  image_url text not null,
  badge text check (badge is null or char_length(badge) <= 40),
  accent_color text not null default '#7affb9' check (accent_color ~ '^#[0-9A-Fa-f]{6}$'),
  stock integer not null default 0 check (stock >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  customer_user_id uuid references auth.users(id) on delete set null,
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  postal_code text not null,
  address text not null,
  payment_method public.payment_method not null,
  payment_status public.payment_status not null default 'pending',
  total_cents integer not null check (total_cents >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  product_name text not null,
  size text not null,
  unit_price_cents integer not null check (unit_price_cents >= 0),
  quantity integer not null check (quantity > 0)
);

create index products_active_category_idx on public.products (is_active, category);
create index products_slug_idx on public.products (slug);
create index orders_created_at_idx on public.orders (created_at desc);
create index order_items_order_id_idx on public.order_items (order_id);

create table app_private.project_heartbeat (
  id boolean primary key default true check (id),
  last_checked_at timestamptz not null default now(),
  check_count bigint not null default 0 check (check_count >= 0)
);
revoke all on table app_private.project_heartbeat from public, anon, authenticated;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();
create trigger products_set_updated_at before update on public.products
for each row execute function public.set_updated_at();
create trigger orders_set_updated_at before update on public.orders
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name')
  )
  on conflict (id) do update
  set email = excluded.email,
      display_name = coalesce(excluded.display_name, public.profiles.display_name);
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy "profiles: user may read own profile"
on public.profiles for select to authenticated
using ((select auth.uid()) = id);

create policy "profiles: admin may read all profiles"
on public.profiles for select to authenticated
using ((select public.is_admin()));

create policy "products: public may read active catalog"
on public.products for select to anon, authenticated
using (is_active = true or (select public.is_admin()));

create policy "products: admin may insert"
on public.products for insert to authenticated
with check ((select public.is_admin()));

create policy "products: admin may update"
on public.products for update to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "products: admin may delete"
on public.products for delete to authenticated
using ((select public.is_admin()));

create policy "orders: admin may read and update"
on public.orders for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "order items: admin may read"
on public.order_items for select to authenticated
using ((select public.is_admin()));

create or replace function public.create_checkout_order(
  p_customer_name text,
  p_customer_email text,
  p_customer_phone text,
  p_postal_code text,
  p_address text,
  p_payment_method public.payment_method,
  p_items jsonb
)
returns table (order_id bigint, order_number text, total_cents integer)
language plpgsql
security definer
set search_path = ''
as $$
declare
  requested record;
  requested_item record;
  product_row public.products%rowtype;
  created_order_id bigint;
  created_order_number text;
  calculated_total integer := 0;
  item_size text;
  item_quantity integer;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'O carrinho não pode estar vazio';
  end if;

  if char_length(trim(p_customer_name)) < 2
    or char_length(trim(p_customer_email)) < 5
    or char_length(trim(p_customer_phone)) < 8
    or char_length(trim(p_postal_code)) < 8
    or char_length(trim(p_address)) < 5 then
    raise exception 'Dados do cliente inválidos';
  end if;

  -- Agrega os itens antes de validar estoque, impedindo que itens repetidos ultrapassem o limite.
  for requested in
    select (value ->> 'productId')::bigint as product_id,
           sum((value ->> 'quantity')::integer) as quantity
    from jsonb_array_elements(p_items)
    group by (value ->> 'productId')::bigint
  loop
    select * into product_row
    from public.products
    where id = requested.product_id and is_active = true
    for share;

    if not found then
      raise exception 'Um dos produtos selecionados não está disponível';
    end if;

    if requested.quantity is null or requested.quantity < 1 or requested.quantity > product_row.stock then
      raise exception 'A quantidade solicitada não está disponível em estoque';
    end if;
  end loop;

  created_order_number := 'OM-' || to_char(now(), 'YYMMDDHH24MISS') || '-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6));

  insert into public.orders (
    order_number, customer_user_id, customer_name, customer_email, customer_phone,
    postal_code, address, payment_method, payment_status, total_cents
  ) values (
    created_order_number, auth.uid(), trim(p_customer_name), lower(trim(p_customer_email)), trim(p_customer_phone),
    trim(p_postal_code), trim(p_address), p_payment_method, 'pending', 0
  ) returning id into created_order_id;

  for requested_item in select value from jsonb_array_elements(p_items)
  loop
    item_size := trim(requested_item.value ->> 'size');
    item_quantity := (requested_item.value ->> 'quantity')::integer;

    select * into product_row
    from public.products
    where id = (requested_item.value ->> 'productId')::bigint and is_active = true;

    if item_size is null or item_size = '' or not (product_row.sizes ? item_size) then
      raise exception 'O tamanho selecionado não está disponível para este produto';
    end if;

    insert into public.order_items (order_id, product_id, product_name, size, unit_price_cents, quantity)
    values (created_order_id, product_row.id, product_row.name, item_size, product_row.price_cents, item_quantity);

    calculated_total := calculated_total + (product_row.price_cents * item_quantity);
  end loop;

  update public.orders set total_cents = calculated_total where id = created_order_id;
  return query select created_order_id, created_order_number, calculated_total;
end;
$$;

revoke all on function public.create_checkout_order(text, text, text, text, text, public.payment_method, jsonb) from public;
grant execute on function public.create_checkout_order(text, text, text, text, text, public.payment_method, jsonb) to anon, authenticated;

create or replace function app_private.record_project_heartbeat()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into app_private.project_heartbeat (id, last_checked_at, check_count)
  values (true, now(), 1)
  on conflict (id) do update
  set last_checked_at = excluded.last_checked_at,
      check_count = app_private.project_heartbeat.check_count + 1;
end;
$$;

-- Toda segunda-feira às 09:00 UTC. Este job é interno e não expõe URL nem chave no GitHub.
select cron.schedule(
  'overzied-weekly-project-check',
  '0 9 * * 1',
  $$select app_private.record_project_heartbeat();$$
);
